### ISSUE TITLE
Only 10 rows are displayed when there are a lot of doctypes

### ISSUE THREAD

**Issue by frankrousseau** [doubleface/cozy-databrowser#30]
Hello @doubleface,

Thank you for your work on the Data Browser. Here is my first bug report!

When you have many doc types, it's not intuitive to scroll down to the very end of the browser window to display more result. At the beginning I thought I can't display more results.

**Comment by doubleface** [comment]
I totally agree with you! My goal here is to display a classical pager with the number of pages (and maybe more items per page as you suggest). What do you think about it?

**Comment by frankrousseau** [comment]
Yes, the traditional pager with more results will make things simpler.

Making the left menu "fixed", would be nice too.
