### ISSUE TITLE
Duplicates in the left column

### ISSUE THREAD

**Issue by nicofrand** [doubleface/cozy-databrowser#36]
Sometimes there are duplicates in the left column, like in this example with the "Tag" table:

![bug-databrowser-duplicate](https://cloud.githubusercontent.com/assets/3419050/10994144/a8e45966-8474-11e5-9e76-388dfe3e5e51.png)

Both have the same content.

**Comment by doubleface** [comment]
This one seems related to #37 . I will look at it

**Comment by doubleface** [comment]
Duplicate
