### ISSUE TITLE
Wrong entries count in the sidebar

### ISSUE THREAD

**Issue by nicofrand** [doubleface/cozy-databrowser#37]
The number of entries is wrong in this example: in the left sidebar I can read "1" whereas there are 2 entries in the table:

![bug-databrowser-wrong-count](https://cloud.githubusercontent.com/assets/3419050/10994365/3c7f9126-8476-11e5-92d2-381d63eccb3a.png)

**Comment by doubleface** [comment]
Thanks for the report, I will try to rerproduce it as soon as possible

**Comment by roukydesbois** [comment]
+1

**Comment by doubleface** [comment]
This is fixed in the future v2 version
