### ISSUE TITLE
Wrong entries in table

### ISSUE THREAD

**Issue by nicofrand** [doubleface/cozy-databrowser#38]
I often meet this issue but it does not happen each time I try to reproduce it.

**Steps to reproduce:**
1. Open a table with at least 10 entries
2. Scroll down to add the remaining entries (since by default only 10 are displayed)
3. Scroll to the top
4. Scroll to the bottom again

**What happens:**

Some entries are displayed but they are not from the current table. In the following example the "Binary" entries are not expected.

![bug-databrowser-wrong-entries](https://cloud.githubusercontent.com/assets/3419050/10994957/c76a8cac-8479-11e5-88d9-cc51c783ceff.png)

**Comment by doubleface** [comment]
Thanks for the report, I will try to rerproduce it as soon as possible

**Comment by doubleface** [comment]
I am working on a new version of the databrowser which won't use this kind of paging. This will then be fixed

**Comment by doubleface** [comment]
This is fixed in the next V2
