### ISSUE TITLE
Build files size issue

### ISSUE THREAD

**Issue by nicofrand** [doubleface/cozy-databrowser#46]
There must be something wrong with the size of this file (which is not minified BTW): https://github.com/doubleface/cozy-databrowser/blob/client/build/app.css.

1.49 MB !

**Comment by doubleface** [comment]
You are right! I did not check the size of the build at all. I will fix this

**Comment by doubleface** [comment]
The responsible for this is font-awesome, just for one icon I use. I will use a simpler and lighter solution

**Comment by doubleface** [comment]
Fixed by 55eba855bbbbdeef24362205214ead4c8466849d
